name: build_and_check

on:
  push:
    # Publish `master` as Docker image.
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  # Build images to DockerHub.
  build_image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Build and push shells images
        run: |
          ./build_image.sh
