name: build

on:
  push:
    # Publish `master` as Docker image.
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

env:
  DOCKER_USERNAME: okadash

jobs:

  # Check action of the build script and workflow
  check_build_script:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: check build script and make command line output
        run: |
          JUST_SAYING=1 ./build_image.sh

  # Build and push image to DockerHub.
  push_image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Build and ship docker images
        run: |
          DOCKER_PUSHING=1 ./build_image.sh
